name: Test

on:
  pull_request_target:
    branches:
      - main
    paths:
      - 'grapevine-api/**'
      - '*.json'
      - '*.yaml'
      - '.github/workflows/**'

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: github-runner
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: ðŸ§¹ Clean pnpm cache and install dependencies
        run: |
          rm -rf node_modules pnpm-lock.yaml
          rm -rf grapevine-api/node_modules
          pnpm install
      - name: ðŸš¦ test grapevine-api
        run: pnpm test --filter=grapevine-api
